import Head from 'next/head'
import { FooterSimple } from '../components/FooterSimple';
import { HeaderResponsive } from '../components/HeaderResponsive';
import { HeroBullets } from '../components/HeroBullets';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Co2-Hammer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderResponsive links={[{
        "link": "/about",
        "label": "Startseite"
      },
      {
        "link": "/pricing",
        "label": "Preise"
      },
      {
        "link": "/community",
        "label": "Team"
      }]} />
      <HeroBullets />
      <FooterSimple links={[
        {
          "link": "#",
          "label": "Contact"
        },
        {
          "link": "#",
          "label": "Privacy"
        },
        {
          "link": "#",
          "label": "Blog"
        },
        {
          "link": "#",
          "label": "Careers"
        }
      ]} />
    </div>
  )
}
